---
- name : install  webserver
  yum :
    name : httpd
    state : present 


- name : copy proxy config 
  copy :
    src : roles/apache/files/student.proxy.conf
    dest : /etc/httpd/conf.d/student_proxy.conf
  vars :
    - student




- name : Download default index page 
  get_url : 
    url : https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest : /var/www/html/index.html
    mode : 0644

- name : Restart Web service
  service :
    name : httpd
    state : restarted
